// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44368' | (string & {});
};

export type DictionaryEntryModel = {
    key: string;
    translations: {
        [key: string]: string;
    };
};

export type GetDictionaryEntriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/lexicon/api/v1/dictionary-entries';
};

export type GetDictionaryEntriesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetDictionaryEntriesResponses = {
    /**
     * OK
     */
    200: Array<DictionaryEntryModel>;
};

export type GetDictionaryEntriesResponse = GetDictionaryEntriesResponses[keyof GetDictionaryEntriesResponses];
